# Generated by Django 3.1.1 on 2020-09-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=200)),
                ('vendorname', models.CharField(db_index=True, max_length=200, unique=True)),
                ('joiningdate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('vendorcontact', models.CharField(db_index=True, max_length=14)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
