# Generated by Django 3.1.1 on 2020-09-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MilkCategory', to='dairyapp.vendor')),
            ],
        ),
    ]
