# Generated by Django 3.1.1 on 2020-09-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_milkcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_milkcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairyapp.milkcategory')),
                ('related_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorledger', to='dairyapp.vendor')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
