# Generated by Django 3.1.1 on 2020-09-28 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(choices=[('Cow', 'Cow'), ('Buffaloe', 'Buffalo'), ('Others', 'Others')], max_length=200)),
                ('milkprice', models.FloatField(db_index=True, max_length=200)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerMilkCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customerledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=1000000)),
                ('price', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('quantity', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('total', models.FloatField(db_index=True, default=0.0, max_length=1000000)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to=settings.AUTH_USER_MODEL)),
                ('related_milk_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customerledger', to='dairyapp.customermilkcategory')),
            ],
        ),
    ]
